[algokit]
min_version = "v2.0.0"

[project]
type = "frontend"
name = 'zkp_vault-frontend'
artifacts = "src/contracts"

[project.run]
build = { commands = ['pnpm run build'], description = 'Build frontend' }
test = { commands = ['pnpm run test'], description = 'Run frontend tests' }
lint = { commands = ['pnpm run lint'], description = 'Lint frontend code' }
ci-deploy-vercel = { commands = [
    'pnpm install --global vercel@latest',
    'pnpm run ci:vercel:pull',
    'pnpm run ci:vercel:deploy',
  ], description = 'Deploy to Vercel' }
